name: e_commerce_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  money_formatter: ^0.0.5
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  pinput: ^5.0.1
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_auth: ^6.0.1
  file_picker: ^10.3.2
  intl: ^0.19.0
  flutter_svg: 

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  
  assets:
    - assets/images/
  

