// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYQsfXiW2ARyTLqsTz_agnMfuHcaxGH4E',
    appId: '1:436519925113:web:81c3905951dfba4bdcaba8',
    messagingSenderId: '436519925113',
    projectId: 'e-com-theo',
    authDomain: 'e-com-theo.firebaseapp.com',
    storageBucket: 'e-com-theo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1_rM1-ngvrZtgGfH3Grg8nsZ2O70SlOU',
    appId: '1:436519925113:android:a720b8ffae92c53adcaba8',
    messagingSenderId: '436519925113',
    projectId: 'e-com-theo',
    storageBucket: 'e-com-theo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVPi2jvIDGXdEzDL-Qptev_6hgHx7leWo',
    appId: '1:436519925113:ios:b4f66260fba9c1bfdcaba8',
    messagingSenderId: '436519925113',
    projectId: 'e-com-theo',
    storageBucket: 'e-com-theo.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

}